api_users_me:
    path: /api/users/me
    methods: GET
    controller: App\Controller\ApiUsersController::getCurrentUser

api_users_register:
    path: /api/users/register
    methods: POST
    controller: App\Controller\ApiUsersController::registerUser
